# Generated by Django 5.0.4 on 2024-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='down_image',
            field=models.ImageField(blank=True, null=True, upload_to='down_poses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='front_poses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to='side_poses/'),
        ),
    ]
