# Generated by Django 5.0.4 on 2024-04-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0003_user_down_image_user_front_image_user_side_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_encoding',
        ),
        migrations.AddField(
            model_name='user',
            name='face_encodings',
            field=models.JSONField(default=list),
        ),
    ]
